name: 'Deploy to Render'
description: 'Deploy your Render app through GitHub Actions'
author: 'JorgeLNJunior'
inputs:
  service_id:
    required: true
    description: 'Render service id'
  api_key:
    required: true
    description: 'Render api key'
  clear_cache:
    required: false
    default: 'false'
    description: 'Clear build cache'
  wait_deploy:
    required: false
    default: 'false'
    description: 'Wait until the deploy status is successful'
  github_deployment:
    required: false
    description: 'Creates a github deployment'
    default: 'false'
  github_token:
    required: true
    description: 'Github auth token'
  deployment_environment:
    required: false
    description: 'The name of the GitHub deployment environment'
    default: 'production'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'
  color: 'green'
