name: 'Deploy to Render'
description: 'Trigger a Render service deploy'
author: 'JorgeLNJunior'
inputs:
  service_id:
    required: true
    description: 'Render service id'
  api_key:
    required: true
    description: 'Render api key'
  clear_cache:
    required: false
    default: false
    description: 'Clear build cache'
  wait_deploy:
    required: false
    default: false
    description: 'Wait until the deploy status is successful'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'
  color: 'green'
